fix: switch how we do http requests to fix socket disconnect error
This keeps happening on decaf and cathy's CI...

🔄 Verifying that the new release was created by re-running the get-latest-release step...
I will set the git committer config to the user provided values: name: github-actions[bot], email: 41898282+github-actions[bot]@users.noreply.github.com
 $> deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases get
Latest git tag on the current branch is: 0.5.1
latest release found: 0.5.1 (0.5.1)
commit matching release found: fix: attach readme to the deno module. because, you know, you need docs (#8) (44b0c3d0915014aa925a2c5fbe91329278f6abf2)
Warning: ⚠️ Verification failed, but that could be expected in test mode. The latest release after deployment is 0.5.1, but expected 0.6.0. This could indicate a problem with the deployment process.
🎉 Congratulations! The deployment process has completed. Bye-bye 👋!
error: Uncaught (in promise) Error: socket hang up
    at connResetException (ext:deno_node/internal/errors.ts:1969:14)
    at node:http:512:30

this is an attempt to fix it